INSERT INTO GEBRUIKER(ID, USERNAME, PASSWORD, algorithm)
VALUES (1, 'Chris', 'pass', 'BCRYPT');

INSERT INTO AUTHORITY(ID, AUTHORITY, USERID)
VALUES(1, 'READ', '1');

INSERT INTO AUTHORITY(ID, AUTHORITYNAME, USERID)
VALUES(2, 'WRITE', '2');

INSERT INTO GUITAR(ID, BRAND, MODEL, GENRE)
VALUES(1, 'Fender', 'Stratocaster', 'All-Round');

INSERT INTO GUITAR(ID, BRAND, MODEL, GENRE)
VALUES(2, 'Gibson', 'Les Paul', 'Heavey, Rock');
